Repository projectmesa/mesa-frames, pull requests merged in 2024-09, with the labels that each got.

#97 Adding GH Issue Templates
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: enhancement, maintenance

#99 Update LICENSE to Apache 2.0
  LICENSE
Labels: maintenance

#100 Add `.idea/` to gitignore for PyCharm
  .gitignore
Labels: ignore-for-release
