Repository projectmesa/mesa-frames, pull requests merged in 2025-07, with the labels that each got.

#165 fix #163: bug selecting attributes from multiagent agentsdf raises an error if attribute not in every agent
  mesa_frames/concrete/agents.py
  mesa_frames/concrete/agentset.py
  tests/test_agents.py
  tests/test_agentset.py
Labels: bug, testing

#148 Rename 'agents' property to 'df' for AgentContainer for issue # 68
  README.md
  docs/general/user-guide/1_classes.md
  docs/general/user-guide/2_introductory-tutorial.ipynb
  examples/boltzmann_wealth/performance_plot.py
  examples/sugarscape_ig/ss_polars/agents.py
  mesa_frames/abstract/agents.py
  mesa_frames/abstract/space.py
  mesa_frames/concrete/agents.py
  mesa_frames/concrete/agentset.py
  tests/test_agents.py
  tests/test_agentset.py
  tests/test_grid.py
Labels: docs, enhancement, breaking, testing

#161 Feature/concrete-data-collector
  .github/workflows/build.yml
  mesa_frames/abstract/datacollector.py
  mesa_frames/concrete/datacollector.py
  pyproject.toml
  tests/test_datacollector.py
Labels: feature
